image: node:latest

before_script:
  - npm install

cache:
  paths:
    - node_modules/

stages:
  - deploy

deploy_development:
  stage: deploy
  environment:
    name: development
  script:
    - npm run build
    - npm run deploy
  only:
    - development # Corresponding only to the development branch.